apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nvtenant-manager-role
rules:
  - apiGroups: ["nvtenant.severinsdigitalsolutions.nl"]
    resources: ["securitypolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["nvtenant.severinsdigitalsolutions.nl"]
    resources: ["securitypolicies/status", "securitypolicies/finalizers"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["neuvector.com"]
    resources: ["nvvulnerabilityprofiles"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]