---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - neuvector.com
  resources:
  - nvvulnerabilityprofiles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nvtenant.severinsdigitalsolutions.nl
  resources:
  - securitynotificationpolicies
  - securitypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nvtenant.severinsdigitalsolutions.nl
  resources:
  - securitynotificationpolicies/finalizers
  - securitypolicies/finalizers
  verbs:
  - update
- apiGroups:
  - nvtenant.severinsdigitalsolutions.nl
  resources:
  - securitynotificationpolicies/status
  - securitypolicies/status
  verbs:
  - get
  - patch
  - update
