## Append samples of your project ##
resources:
- nvtenant_v1alpha1_securitypolicy_ns_a.yaml
- nvtenant_v1alpha1_securitypolicy_ns_b.yaml
- nvtenant_v1alpha1_securitynotificationpolicy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
