apiVersion: nvtenant.severinsdigitalsolutions.nl/v1alpha1
kind: SecurityNotificationPolicy
metadata:
  labels:
    app.kubernetes.io/name: nvtenant-operator
    app.kubernetes.io/managed-by: kustomize
  name: securitynotificationpolicy-sample
spec:
  # TODO(user): Add fields here
